### ISSUE TITLE
How do I custom status ?

### ISSUE THREAD

**Issue by qnkhuat** [hughbien/thyme#2]
Hi, 

Can you give an example of how do I custom my status-right.
Or more specifically how do I store the thyme status and `cat` it on tmux status-right

Thank you for building this ^^

**Comment by hughbien** [comment]
Hi! To set a custom status-right, you'll need to prevent Thyme from setting it. In `~/.thymerc` put:

```yml
status_override: false
```

When you start thyme, it writes out the timer this file: `~/.thyme-tmux`.  You can read from it to set your status.

Finally, to set your own status you'll need to configure tmux. In `~/.tmux.conf`:

```
set -g status-right '#(cat ~/.thyme-tmux)'
set -g status-interval 1
```

The above will set the default status-right. You can put anything in place of `#(cat ~/.thyme-tmux)` though, including static strings or you can run your own script.

Let me know if I can help with anything!
