### ISSUE TITLE
Manually start and stop pomodori and breaks

### ISSUE THREAD

**Issue by GCorbel** [hughbien/thyme#21]
Sometimes I want to continue to work or my break so I don't want the timer to be changed automatically. I think it can be useful to have a command like `thyme --next` and a config `set :auto, true`.

What you think ?

**Comment by GCorbel** [comment]
I found a way to do what I want. I did this class : 

```
class ContinuousTimer
  def work(config, in_break, message = '')
    File.delete(RUN_FILE) if File.exist?(RUN_FILE)
    config.repeat = 1
    config.break = in_break
    begin
      File.open(RUN_FILE, 'w') {}
      Timer.new(config).run

      File.open(Config::TMUX_FILE, 'w') { |file| file.write(message) }
      sleep 1 while File.exist?(RUN_FILE)
    ensure
      config.send_to_plugin(:after_all)
    end
  end
end
```

And I added this config : 

```
option :f, 'force', 'force to stop' do
  File.delete(RUN_FILE) if File.exist?(RUN_FILE)
  Timer.new(self).stop
end

option :w, 'work [SECONDS]', 'run only the work time' do |num|
  set :timer, num.to_i if num
  ContinuousTimer.new.work(self, false, 'Time to take a break')
end

option :b, 'break [SECONDS]', 'run only the break time' do |num|
  set :timer_break, num.to_i if num
  ContinuousTimer.new.work(self, true, 'Time to work')
end
```

I can do `thyme -w`, `thyme -b` and `thyme -f` to do what I want. It's little bit a hack but it works. I added some shortcuts in tmux to make it easy.

Do you think it's useful and it could be added in the core ?

**Comment by hughbien** [comment]
Looks like a great workflow! I think it'd be best served as a Thyme plugin as opposed to being merged into the core.
