### ISSUE TITLE
Log hours in a file

### ISSUE THREAD

**Issue by GCorbel** [hughbien/thyme#23]
I did a copy/paste of the read me and the `run` method is not available with `--seconds`. I have to do `Timer.new(self).run` instead. I think this should be corrected.

I created a little plugin to log all hours I do for a project. Here is the code : 

```
require 'json'
class MyThymePlugin
  def initialize(thyme)
  end

  def before_all
    @start_date = DateTime.now
  end

  def after_all
    elapsed_time = ((DateTime.now - @start_date) * 24 * 60 * 60).to_i

    session_name = `tmux display-message -p '#S'`.chomp
    file_path = "#{ENV['HOME']}/.timer"
    file = File.read(file_path)
    data = JSON.parse(file)

    data[session_name] ||= {}
    if data[session_name][Date.today.to_s]
      data[session_name][Date.today.to_s] += elapsed_time
    else
      data[session_name][Date.today.to_s] = elapsed_time
    end

    File.write(file_path, JSON.dump(data))
  end
end

use MyThymePlugin
```

It's simple but it works. Let me know if you want I integrate it in your project.

**Comment by hughbien** [comment]
This looks awesome! I think it's a bit beyond the core feature set of Thyme, but would make a great a plugin.
